### ISSUE TITLE
Tests fail after upgrading to ex-navigation 3.0.0

### ISSUE THREAD

**Issue by gcarling** [expo/ex-navigation#480]
After upgrading to react-native 0.44.2 and subsequently upgrading to ex-navgation 3.0.0, all of my tests have started failing with this error:

  ```
  TypeError: Cannot read property 'style' of undefined

      at Object.<anonymous> (node_modules/@expo/ex-navigation/src/navigation-experimental/NavigationCardStack.js:312:451)
      at Object.<anonymous> (node_modules/@expo/ex-navigation/src/navigation-experimental/index.js:14:25)
      at Object.<anonymous> (node_modules/@expo/ex-navigation/src/ExNavigationReducer.js:3:29)
```

These are the versions of packages I'm currently using:

"@expo/ex-navigation": "3.0.0",
"react": "16.0.0-alpha.6",
"react-native": "0.44.2",
"jest": "20.0.4",

If I go back to ex-navigation 2.9.2 the tests run fine, even with the new versions of react and react-native.  I haven't been able to find anything about this online, but I also have had no luck debugging the issue. Curious if anyone else has run into the same thing.

**Comment by gcarling** [comment]
Turned out we were using `react-native-mock` which hasn't been updated for most recent react-native versions. Closing
